# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./EmbyPluginUiDemo.sln
    - name: Build
      run: dotnet build ./Emby.Jimaku.csproj --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      # Upload all archives even if one of the zips fails to upload
      if: success()
      with:
        name: Emby.Jimaku
        path: ./bin/Debug/netstandard2.0/Emby.Jimaku.dll
        compression-level: 0
